name             "monit_bin"
maintainer       "HiganWorks LLC"
maintainer_email "sawanoboriyu@higanworks.com"
license          "MIT"
description      "Installs/Configures monit_bin"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "1.1.2"
supports         "ubuntu"
supports         "smartos"
supports         "debian"
